### ISSUE TITLE
Fix wiki links

### ISSUE THREAD

**Issue by femtotrader** [OpenTrading/OpenTrader#2]
Hi,

some wiki links should be fixed

```
https://github.com/OpenTrading/wiki/RoadMap
```

->

```
https://github.com/OpenTrading/OpenTrader/wiki/RoadMap
```

Search `OpenTrading/wiki`

Kind regards

**Comment by OpenTrading** [comment]
Thanks for spotting these - they should be fixed now.

**Comment by femtotrader** [comment]
Maybe you should also fix

https://github.com/OpenTrading/OTMql4AMQP)

## 

https://github.com/OpenTrading/OTMql4Lib)

## 

https://github.com/ematvey/pybacktest/)

## 

https://github.com/OpenTrading/OpenTrader/wiki/TaLib)

## 

http://matplotlib.org%29/

## 

http://rabbitmq.org%29/

**Comment by OpenTrading** [comment]
I think I have them all fixed; it's a bug in GitHub's creole formatting, that doesn't
show up in the wiki pages, but if a the same page is put as a README.creole, then
it mkaes these formatting errors. Haven;t had the time to chase where on github the
code is, and won't bother now that we have a workaround.
